config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :show] do
     collection do
      get 'next_unswiped'
    end
  end

  resources :users, only: [:show, :create, :new, :edit, :update, :destroy]

  resources :match_restaurants, only: [:show, :create] do
    member do
      get :success
    end
  end
  resources :swipes, only: [:create]
  resources :match_users, only: [:create, :show] do
    member do
      get :success
    end
    member do
      get :unsuccess
    end

    member do
      get :novote
    end
  end
  resources :conversations, only: [:show, :create, :new]

  resources :messages, only: [:create, :new, :show] #mby not new

  resource :session, only: [:new, :create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  get '/about' => 'pages#about'

  root 'restaurants#index'

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	has_many :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create

  end

  def new

  end

  def show
    @message = Message.new
    @conversation = Conversation.find_by(id: params[:id])
    @match_user = MatchUser.where(creator_id: @conversation.sender_id, target_id: @conversation.recipient_id).first
    @all_messages = @conversation.messages
    @recipient = User.find_by(id: @conversation.recipient_id)
  end
end

app/views/conversations/show.html.erb
<% chat_partner = @match_user.other_user(current_user) %>

<h1>Chat with <%= link_to chat_partner.name, user_path(chat_partner)%>!</h1>

<div id="chat-messages">
   <%= render @conversation.messages %>
</div>

<div id='message-bar'>
<h2> Submit a new message:</h2>
<%= form_for @message, remote: true, url: messages_path do |f| %>
Content: <%=f.text_area :content%>
<%= f.hidden_field :match_user_id, value: @match_user.id%>
<%= f.hidden_field :conversation_id, value: @conversation.id%>
<%= f.submit "Send"%>
<%end%>
</div>
<%= subscribe_to conversation_path(@conversation) %>