config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :show] do
     collection do
      get 'next_unswiped'
    end
  end

  resources :users, only: [:show, :create, :new, :edit, :update, :destroy]

  resources :match_restaurants, only: [:show, :create] do
    member do
      get :success
    end
  end
  resources :swipes, only: [:create]
  resources :match_users, only: [:create, :show] do
    member do
      get :success
    end
    member do
      get :unsuccess
    end

    member do
      get :novote
    end
  end
  resources :conversations, only: [:show, :create, :new]

  resources :messages, only: [:create, :new, :show] #mby not new

  resource :session, only: [:new, :create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  get '/about' => 'pages#about'

  root 'restaurants#index'

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true

  has_secure_password

  has_many :interest_users
  has_many :interests, through: :interest_users

  has_and_belongs_to_many(:users,
    :join_table => "match_users",
    :foreign_key => "creator_id",
    :association_foreign_key => "target_id")

  has_many :restaurants, through: :match_restaurants

  has_many :swipes_as_swipee, foreign_key: :swipee_id, class_name: "Swipe"
  has_many :swipes_as_swiper, foreign_key: :swiper_id, class_name: "Swipe"
  has_many :swiped_users, through: :swipes_as_swiper, source: :swipee, foreign_key: :swipee_id
  has_many :swipers, through: :swipes_as_swipee, source: :swiper, foreign_key: :swiper_id
  has_many :match_restaurants

  def open_connections
    all_mus = MatchUser.where(creator_id: self.id).where(status: 'active').where(accepted: true) + MatchUser.where(target_id: self.id).where(status: 'active').where(accepted: true)
    all_mus.flatten
  end

  def interests_as_string
    self.interests.pluck(:name).join(", ");
  end

  def common_interests(usertwo)
    self.interests.select do |interest|
      usertwo.interests.include? (interest)
    end
  end

  def self.from_omniauth(auth)
    where(provider:auth[:provider], uid:auth[:uid]).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.password = SecureRandom.uuid
      user.save!
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_current_user

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "Thanks for registering"
      redirect_to edit_user_path(user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @user.name = @user.name.capitalize
    @match_restaurants = @user.match_restaurants.where(match: true)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    interests_array = user_params[:interests].split(",")
    interests_array.map! {|interest_name| interest_name.downcase.strip}
    interests_array.map! {|interest| Interest.find_or_create_by(name: interest)}
    interests_array.uniq!
    updateable_params = user_params.dup
    updateable_params.delete(:interests)

    if @user.update(updateable_params)
      @user.interest_users.each { |im| im.destroy}
      interests_array.each do |new_interest|
        @user.interests << new_interest
      end
      flash.notice = 'User profile saved'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :age, :background_information, :is_desperate, :interests)
  end

end

app/views/users/edit.html.erb
<%= form_for @user,:html => {:class => "userform"} do |f| %>
  <fieldset>
    <legend>Fill in Your Details</legend>
      <ul>
        <li>
          <%= f.label :name %>
          <%= f.text_field :name, :class => 'userinput' %>
        </li>
        <li>
          <%= f.label :age %>
          <%= f.text_field :age, :class => 'userinput' %>
        </li>
        <li>
          <%= f.label :background_information %>
          <%= f.text_area :background_information, :class => 'userinput' %>
        </li>
        <li>
          <%= f.label :interests %>
          Please list your interests separated by commas.
          <%= f.text_area :interests, value: @user.interests_as_string, :class => 'userinput' %>
        </li>
        <li>
          <%= f.label :is_desperate, "Willing To Pay?" %>
          <%=  f.check_box :is_desperate %>
        </li>
      </ul>
  <%= f.submit "Update", :class => 'usersubmit' %>
  </fieldset>
<% end %>

app/views/users/new.html.erb
<%= form_for @user,:html => {:class => "userform"} do |f| %>
  <fieldset>
    <legend>Create an Account</legend>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'userinput' %>
    </div>

    <div>
      <%= f.label :password %>
      <%= f.password_field :password, :class => 'userinput' %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :class => 'userinput' %>
    </div>

    <div>
      <%= f.submit 'Submit', :class => 'usersubmit' %>
    </div>
  </fieldset>
<% end %>

<% if @user.errors.any? %>
  <div class="error_report">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to <%=@user.name%>'s profile!</h1>
<% if @user == current_user %>
<%= link_to 'edit your profile', edit_user_path(@user) %>
<% end %>

<h2><%=@user.name%>'s profile details below:</h2>
<ul>
  <img src='<%=@user.image%>' style='float:left; padding-right:3em;' height=100px width=150px>
  <li>AGE: <%=@user.age%></li>
  <li>BACKGROUND: <%=@user.background_information%></li>
  <% if @user == current_user %>
  <li>INTERESTS: <%@user.interests.each do |interest|%><%=interest.name%> <%end%></li>
  <% else %>
  <% highlighted_interests = @user.common_interests(current_user) %>
  <li>INTERESTS:
    <% @user.interests.each do |interest| %>
    <% if highlighted_interests.include?(interest) %>
    <span class="highlighted-common-interest"><%= interest.name %></span>
    <% else %>
    <%= interest.name %>
    <% end %>
    <% end %>
    <%end%>
  </li>
  <li>WILLING TO PAY: <%if @user.is_desperate%>Yes<%else%>No<%end%></li>
</ul>


   <% if current_user.open_connections.count > 0 %>
    <% current_user.open_connections.each do |mu|%>
    <% if mu.target == @user %>
    <h3> You've matched with <%= link_to mu.other_user(current_user).name.capitalize, match_user_path(mu) %>! Would you like to chat with them?
    <%end%>
    <%end%>
    <%end%>

<hr />
<div id="restaurant-matches-section">
  <h2>Matched with the following restaurants!</h2>
  <% @match_restaurants.each do |mr| %>
  <div class="restaurant-match-tile">
    <p><% if @user == current_user %>
      <%= link_to mr.restaurant.name, match_restaurant_path(mr.id)%>
      <% else %>
      <% my_match_restaurant = MatchRestaurant.where(user_id: current_user.id).where(restaurant_id: mr.restaurant.id).first %>
      <% if my_match_restaurant%>
      <%= link_to mr.restaurant.name, match_restaurant_path(my_match_restaurant.id)%>
      <% else %>
      <%= mr.restaurant.name %>
      <% end %>
      <% end %></p>
      <p><%= mr.restaurant.cuisine %></p>
    </div>
    <% end %>
  </div>

  <% if @user == current_user %>
  <% if @user.open_connections.count > 0 %>
  <hr />
  <h2>Open Connections!</h2>
  <% @user.open_connections.each do |mu| %>
  <div class='user-match-tile'>
    <p><%= link_to mu.other_user(@user).name, match_user_path(mu) %><p>
      <% common_interests = @user.common_interests(mu.other_user(@user)) %>
      <% if common_interests.count > 0 %>
      <p>Common interests:
        <% common_interests.each do |interest| %>
        <%= interest.name %> <% end %>
      </p>
      <% end %>
    </div>
    <% end %>
    <% end %>
    <% end %>