config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :show] do
     collection do
      get 'next_unswiped'
    end
  end

  resources :users, only: [:show, :create, :new, :edit, :update, :destroy]

  resources :match_restaurants, only: [:show, :create] do
    member do
      get :success
    end
  end
  resources :swipes, only: [:create]
  resources :match_users, only: [:create, :show] do
    member do
      get :success
    end
    member do
      get :unsuccess
    end

    member do
      get :novote
    end
  end
  resources :conversations, only: [:show, :create, :new]

  resources :messages, only: [:create, :new, :show] #mby not new

  resource :session, only: [:new, :create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  get '/about' => 'pages#about'

  root 'restaurants#index'

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]

end

app/models/match_restaurant.rb
class MatchRestaurant < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  validates_uniqueness_of :user, scope: :restaurant

  def self.return_matchable_users(current_user)
    self.all.reject{|mr| mr.user.swipers.select{|swiper| swiper.id == current_user.id}.any? || mr.user.swipers.select{|swipee| swipee.id == current_user.id}.any?}.map{|mr| mr.user}
  end
end

app/controllers/match_restaurants_controller.rb
class MatchRestaurantsController < ApplicationController
  def create

    @matchrestaurant = MatchRestaurant.create!(matchrestaurant_params)

    if request.xhr?

      if @matchrestaurant.match && @matchrestaurant.is_permanent
        status = "always"
      elsif @matchrestaurant.match && !@matchrestaurant.is_permanent
        status = "yes"
      elsif !@matchrestaurant.match && @matchrestaurant.is_permanent
        status = "never"
      else
        status = "no"
      end

      send_back = {restaurant_name: @matchrestaurant.restaurant.name, matchrestaurant_id: @matchrestaurant.id, stat: status, image_url: @matchrestaurant.restaurant.image_url}
      render :json => send_back

    else
      if @matchrestaurant.match
        redirect_to success_match_restaurant_path(@matchrestaurant)
      else
        redirect_to restaurants_path
      end
    end
  end

  def new

  end

  def show
    @match_restaurant = MatchRestaurant.find(params[:id])
    @true_matches = MatchRestaurant.where(restaurant_id: @match_restaurant.restaurant.id, match: true)
    @matchable_users = @true_matches.return_matchable_users(current_user).reject {|user| user == current_user}
    nil_check
  end

  def success
    @match_restaurant = MatchRestaurant.find(params[:id])
    @restaurant = @match_restaurant.restaurant
    render '/match_restaurants/_success'
  end

  def matchrestaurant_params
    params.permit(:restaurant_id, :match, :is_permanent,).merge(user: current_user)
   end

   private
   def nil_check
    if @matchable_users == []
      @show_page_greeting = "You have swiped on every user who has liked this restaurant in the past 24 hours."
    else
      @show_page_greeting = "The following users have also selected #{@match_restaurant.restaurant.name}."
    end
   end
end

app/views/match_restaurants/_success.html.erb
<h1> Congratulations, you matched with <%= @restaurant.name%>!</h1>
<p> Would you like to:</p>
<%= link_to "Search for users now!", match_restaurant_path(@match_restaurant.id)%>
<p>OR</p>
<%= link_to "Keep swiping!", restaurants_path%>

app/views/match_restaurants/show.html.erb
<h1><%=@match_restaurant.restaurant.name%></h1>
<%= @show_page_greeting%>

<div id="matchable-users">
  <% @matchable_users.each do |user|%>
  <div class="card">
    <div class='front'>
      <%=link_to user.name, user, class:'user-card-name'%>
      <% if user.is_desperate == true %>
      <%= image_tag('cash.png', size: "25x25") %>
      <% end %>
      <div id='propic'>
        <%= image_tag(user.image, size:"200x200", class: "user-tile-profile-picture")%>
      </div>
      <div class="yes-no-buttons" data-id=<%= user.id %>>
        <%= form_tag swipes_path, class: "user-swipe-yes" do %>
        <%= hidden_field_tag :swipee_id, user.id%>
        <%= hidden_field_tag :direction, true%>
        <%= hidden_field_tag :restaurant_id, @match_restaurant.restaurant_id%>
        <%= hidden_field_tag :match_restaurant_id, @match_restaurant.id%>
        <%= submit_tag "Yes", class: "submit-yes-swipe", :name => nil %>
        <% end %>

        <%= form_tag swipes_path, class: "user-swipe-no" do %>
        <%= hidden_field_tag :swipee_id, user.id%>
        <%= hidden_field_tag :direction, false%>
        <%= hidden_field_tag :restaurant_id, @match_restaurant.restaurant_id%>
        <%= hidden_field_tag :match_restaurant_id, @match_restaurant.id%>
        <%= submit_tag "No", class: "submit-no-swipe", :name => nil %>
      </div>
    </div>
      <div class="back"></div>
    <% end %>
  </div>
<%end%>
</div>

<hr />
<h3> Matches: </h3>

<% if @match_restaurant.user.open_connections.count > 0 %>
    <% @match_restaurant.user.open_connections.each do |match_user|%>
      <div class="just-the-name">
        <%= link_to "#{match_user.other_user(current_user).name}", user_path(match_user.other_user(current_user)), class:'user-card-name'%>
      </div>
    <%end%>
<% else %>
  No matches yet.
<% end %>