config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :show] do
     collection do
      get 'next_unswiped'
    end
  end

  resources :users, only: [:show, :create, :new, :edit, :update, :destroy]

  resources :match_restaurants, only: [:show, :create] do
    member do
      get :success
    end
  end
  resources :swipes, only: [:create]
  resources :match_users, only: [:create, :show] do
    member do
      get :success
    end
    member do
      get :unsuccess
    end

    member do
      get :novote
    end
  end
  resources :conversations, only: [:show, :create, :new]

  resources :messages, only: [:create, :new, :show] #mby not new

  resource :session, only: [:new, :create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  get '/about' => 'pages#about'

  root 'restaurants#index'

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OKLunch</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Flamenco' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Asap' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
</head>

<body>
    <div class="container">
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "OKLunch", about_path, :class => 'navbar-brand' %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", restaurants_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><a href="https://github.com/nyc-chorus-frogs-2016/OKLunch">On GitHub</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li class="p15">Signed in as <strong><%= link_to current_user.name, user_path(current_user.id) %></strong>!</li>
              <li><%= link_to "Sign out", logout_path, id: "sign_out" %></li>
              <% else %>
              <li><%= link_to "Register", register_path%></li>
              <li><%= link_to "Login", login_path%></li>
              <li><%= link_to image_tag('fb2.png', size:"90x20"), "/auth/facebook", id: "sign_in" %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>


    </div> <!-- /container -->

  <div> <!-- class="container marketing p10"> -->
  <% if flash.any?  %>
  <div id="flash-container">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "flash-#{name}" %>
    <% end %>
  </div>
  <% end %>

  <div ><!-- class="row"> -->
    <%= yield %>
    </div>
  </div>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>